language: ruby
script: "./script/cibuild"

rvm:
  - 2.1

sudo: false
cache: bundler
services:
  - redis

env:
  global:
    GITHUB_CLIENT_ID: "1234"
    GITHUB_CLIENT_SECRET: "1234"
    REDIS_URL: "redis://127.0.0.1:6379"
